
--exec hammerdb.dbo.cleanup

ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG1'  
   WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT);  
ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG1'  
   WITH (FAILOVER_MODE = AUTOMATIC);


ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG2'  
   WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT);  
ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG2'  
   WITH (FAILOVER_MODE = AUTOMATIC);


ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG1'  
   WITH (AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT);  
ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG1'  
   WITH (FAILOVER_MODE = MANUAL);


ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG2'  
   WITH (AVAILABILITY_MODE = SYNCHRONOUS_COMMIT);  
ALTER AVAILABILITY GROUP AG01 MODIFY REPLICA ON 'LA-SQLAG2'  
   WITH (FAILOVER_MODE = MANUAL);
